name: Fetch AI News Daily

on:
  schedule:
    # Läuft jeden Tag um 05:00 Uhr UTC
    - cron: '0 5 * * *'
  # Erlaubt den manuellen Start des Jobs
  workflow_dispatch:

# HINZUGEFÜGT: Gibt dem Workflow die nötigen Schreibrechte
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script to fetch and summarize news
        run: python fetch_news.py
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "📰 Update daily news and summary"
          # KORRIGIERT: Überwacht jetzt auch die summary.json
          file_pattern: "data.json summary.json"
